remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: true
  volunteer: false

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Data Engineer
  - Data Scientist
  - Data Analyst
  - Data Manager
  - Data Architect
  - Machine Learning Engineer

locations:
  - Argentina
  - Colombia
  - Uruguay
  - Mexico
  - Chile
  - Peru
  - Ecuador
  - Paraguay

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 1500

llm_model_type: gemini
llm_model: 'gemini-pro'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
